config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users, only: [:create, :show]
  resources :cart, only: [:show]
  resources :order_items
  resources :items
  resources :items, only: [:show] do
    post '/purchase' => 'transactions#create'
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many order_items
  belongs_to user
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items
  has_many :reviews
  has_many :transactions
  has_many :users, through: :transactions
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  # belongs_to :user
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end

  private

  def update_subtotal
    self[:subtotal] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def product_present
    if product.nil?
      flash[:error] = "Item Currently Out of Stock"
    end
  end

  def order_present
    if order.nil?
      flash[:error] = "Please add an Item to your Cart Before Checking Out"
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :items
  has_many :users, through: :items
end

app/models/user.rb
class User < ApplicationRecord
  has_many :order_items, :through => :carts
  has_many :reviews
  has_many :items
  has_secure_password

  validates_presence_of :username, allow_blank: false

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end
  #test 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
    @order_item = current_order.order_items.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.valid?
      @item.save
      redirect_to item_path(@item)
    else
      flash[:notice]
      redirect_to 'items/new'
    end
  end

  def show
    @item = Item.find(params[:id])
    @transaction = Transaction.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to item_path(@item)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :quantity, :img_url)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_log_in, except: [:show, :index]

  def index
    @reviews = Review.where(item_id: params[:item_id])
    @item = Item.find_by(id: params[:item_id])
  end

  def new
    @review = Review.new
  end

  def create

    @review = Review.new(user_id: current_user.id, item_id: params[:item_id], content: params[:review][:content])
    @review.item = Item.find(params[:item_id])
    @review.user = current_user
    @review.save

    redirect_to item_path(params[:item_id])
  # else
  #    flash[:error] = "error"
  #   render 'new'
  # end
  end

  def show
    @item = Item.find(params[:item_id])
    @reviews = Review.where(item_id: params[:item_id])
    @review = Review.find(params[:item_id])
    # @user = User.find_by(id: @review.user_id)
    # @item = Item.find_by(id: @review.item_id)
  end

  # private
  #
  # def review_params
  #   params.require(:review).permit(:content, :user_id, :item_id)
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

def create
  # sign in by third party service -- Facebook
  if auth
      user = User.find_by(uid: auth['uid'])
      if !user
        user = User.new(uid: auth['uid'])
        user.password = SecureRandom.hex(9)
        user.name = auth['info']['name']
        user.email = auth['info']['email']
        user.save
      end
    else
      # sign in with username and password
      login_info = params[:user]
      if !login_info[:username] || login_info[:username].empty? || !login_info[:password]
        flash[:error] = "Username and password cannot be blank. Please try again."
        return redirect_to login_path
      end
      user = User.find_by(username: login_info[:username])
      user = user.try(:authenticate, login_info[:password])
      # throw error if incorrect credentials
      if !user
        flash[:error] = "Invalid Username or Password. Please try again."
        return redirect_to login_path
      end
    end
    flash[:success] = "Successfully logged in!"
    session[:user_id] = user.id
    @user = user
    redirect_to root_path
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = "Successfully logged out"
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.valid?
      session[:user_id] = user.id
      @user = user
      @user.save!
      flash[:success] = "Account Successfully Created!"
      redirect_to root_path
    else
      @user = user
      redirect_to 'users/new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :balance)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_cart_list.html.erb
<h4><%= item.name %></h4>
  <%= form_for order_item %>
    <h4>Unit Price: <%= number_to_currency order_item.unit_price %></h4>
    <%= f.number_field :quantity, value: order_item.quantity.to_i %>
    <h4>Total Price: <%= number_to_currency order_item.total_price %></h4>

app/views/carts/_shopping_cart.html.erb
<% if order_items.size === 0 %>
<p>There are no Items in your cart </p>
<% else order_items.each do |item| %>
  <%= render 'carts/cart_list', item: order_item.item, order_item: order_item, show_total: true %>
<% end %>

app/views/carts/show.html.erb
<%= render "shopping_cart" %>

app/views/items/_form.html.erb
    <%= f.label :img_url %> <br>
    <%= f.text_field :img_url, class: :input %> <br> <br>

    <% if params[:id] %>
        <%= link_to 'Back', item_path(item), class: "link back" %>
        <%= f.submit 'Update Listing', class: :button %>
        <%= link_to 'Delete Listing', item_path(item), method: :delete, class: "link back" %>
    <% else %>
        <%= link_to 'Back', root_path, class: "link back" %>
        <%= f.submit 'Create New Listing', class: :button %>
    <% end %>

app/views/items/edit.html.erb
<h2>Edit this item</h2>
<%= render 'form', item: @item %>

app/views/items/index.html.erb
<%= link_to 'Back', root_path, class: "link back" %>
<% if admin? %>
  <%= link_to 'Create Item Listing', new_item_path, class: "button" %>
<% end %>

<h3>All Clothing</h3>
<% @items.each do |item| %>
  <div class='item-index'>
    <div class='container'>
      <a href=<%= item_path(item) %>
        <h4><%= item.name %></h4>
        <p><%= item.description %></p>
        <h4>Price: <%= item.price %>$</h4>
        <h4>In Stock: <%= item.quantity %></h4>
        <img src=<%= item.img_url %>>
      </a>
    </div>
  </div>
<% end %>

app/views/items/new.html.erb
<h3>Add new item</h3>
<%= render 'form', item: @item %>

app/views/items/show.html.erb
<h2><%= @item.name %></h2>
<h3><%= @item.description %></h3>
<h3>$ <%= @item.price %></h3>
<p>Left in stock: <%= @item.quantity %></p>

<% if admin? %>
<%= link_to 'Back', items_path, class: "link back" %>
    <%= link_to 'Edit this item', edit_item_path(@item), class: :edit %>
    <%= link_to 'Remove this item', item_path(@item), method: 'delete', class: 'link delete' %>
<% else %>
    <%= form_for(@transaction, url: item_purchase_path(@item)) do |f| %>
        <%= f.label :quantity %>
        <%= f.number_field :quantity, value: 1 %>
        <%= link_to 'Back', items_path, class: "link back" %>
        <%= f.submit 'Purchase', class: :button %>
    <% end %>
    <br>
    
    <%= link_to 'Write a Review', new_item_review_path(@item) %> |
    <%= link_to 'View all Reviews', item_review_path(@item) %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
<% if user.errors.any? %>
    <div id="error_explanation">
      <h2>There was an error: </h2>
      <ul>
        <% user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<br>
    <%= f.label :username %> <br>
<div class="field <%= ' field_with_errors' if user.errors[:username].any? %>">
    <%= f.text_field :username, class: :input %>
</div>
<br>
<div>
    <%= f.label :password %> <br>
    <%= f.password_field :password, class: :input %>
</div>
<br>
    <%= f.label :balance %> <br>
<div class="field <%= ' field_with_errors' if user.errors[:balance].any? %>">
    <%= f.number_field :balance, step: :any, class: :input %>
</div>
<br><br>
    <%= link_to 'Back', root_path, class: "link back" %>
    <%= f.submit 'Submit', class: :button %>
<% end %>

app/views/users/new.html.erb
<h2>Sign up</h2>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<h3>Balance: <%= @user.balance %></h3>